/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.ithelpm;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test void appHasAGreeting() {
        
    }
}
