/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.ithelpm;

public class App {
    public static void main(String[] args) {
        
    }
    // static String block() {
        
    // }
}
